export const enum ENVIRONMENT_VARIABLES {
  DATABASE_URL = 'DATABASE_URL',
  JWT_ACCESS_EXPIRATION = 'JWT_ACCESS_EXPIRATION',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
}
